name: zego_uikit_prebuilt_live_streaming
description: PrebuiltLiveStreaming is a full-featured live streaming kit that provides realtime video/audio streaming, live text chat, face beautification, and supports unlimited viewers.
version: 3.14.7
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_flutter
screenshots:
  - description: "preview for Live Streaming Kit"
    path: images/preview.jpg
  - description: "preview for Live Streaming Kit"
    path: images/preview_2.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.28.29
  zego_plugin_adapter: ^2.13.12

  permission_handler: ^12.0.1
  flutter_styled_toast: ^2.1.3
  statemachine: ^3.2.0
  collection: ^1.18.0
  floating: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  lints: ^6.0.0

flutter:
  assets:
    - assets/icons/
  plugin:
    platforms:
      android:
        package: com.zegocloud.uikit.prebuilt_live_streaming
        pluginClass: ZegoUIKitPrebuiltLiveStreamingPlugin
      ios:
        pluginClass: ZegoUIKitPrebuiltLiveStreamingPlugin

topics:
  - live
  - livestream
  - livestreaming
  - live-streaming
  - pk

linter:
  rules:
    public_member_api_docs: true